# Generated by Django 5.1.3 on 2024-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='BookApp_boo_price_e9066d_idx'),
        ),
    ]
